<a href="https://colab.research.google.com/github/lazizbeksadullaev/telegram-bot/blob/main/chiziqli_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Matritsalar ustida amallar bilan tanishaylik

In [2]:
import numpy as np

In [4]:
# data
array1 = np.arange(1.,7.).reshape(2,3)# arange da float qilb bersak diapazonni 
# massivni ham float qilib yaratar ekan int qilsak in edi avalgi darslarimizda ko'rdik
array1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
array2 = np.arange(7., 13.).reshape(2,3)
array2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [8]:
array1+array2 # 2 matritsani bir biriga qo'shish

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [9]:
array2-array1 # elementlararo ayirish

array([[6., 6., 6.],
       [6., 6., 6.]])

In [10]:
array1*5 # skalyar ko'paytruv array1 ni 5 ga skalyar ko'paytrdik

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [11]:
# matritsalarni ko'paytrish: nxm x mxp = [nxp] lik matritsa beradi
# * belgi oddiy elementlararoko'paytrb beradi
array1*array2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [12]:
# lekin biz chiziqli algebradagi kabi ko'paytrish uchun
# nxm x mxp = [nxp] lik matritsa beradi qoidaga tushadigan matritsalar 
# olishiumiz kere

In [20]:
# array1.shape = (2,3) uchun array2 ni shapeni (3, 2) ga 
# almashtrib array3 ga yuklimiz:
array3 = array2.reshape(3,2)

In [21]:
array3

array([[ 7.,  8.],
       [ 9., 10.],
       [11., 12.]])

In [23]:
array1.dot(array3) # dot product of array1 and array3-
# -chiziqli algebradaki ko'paytrish(2x3) x (3x2)=(2x2) bo'aldi

array([[ 58.,  64.],
       [139., 154.]])

In [24]:
# yuqoridagini bunday qilish ham mumkin
np.dot(array1, array3)

array([[ 58.,  64.],
       [139., 154.]])

In [25]:
np.dot(array3, array1)# (3x2) x (2x3) = (3x3)

array([[ 39.,  54.,  69.],
       [ 49.,  68.,  87.],
       [ 59.,  82., 105.]])

In [ ]:
import numpy as np

In [27]:
# Numpyni ichida Linear algebra uchun alohida modul boni ham chqirib olishimz mumkin
# linear algebr-linalg qilib import qilingan ekan numpyda 
from numpy.linalg import inv # bu bexto ishlayapti

In [ ]:
from np.linalg import inv # modulenotfound error olyapti, chunki 
# numpy.linalg qilib chaqir deyapti. Lekin man numpy ni np qilib chaqirganmanku
# nega np.lialg import xato beradi?

In [ ]:
inv(array1) # array1(2x3) ning inersion i teskarisini chiqarishi kere deb 
#  o'ylay olmaymiz chunki LinAlgError olamiz:  Last 2 dimensions of the array must be square

In [34]:
# Shu sabab square massiv yaratylik:
array4 = np.arange(1,10).reshape(3,3)
array4[0,0]=13
array4

array([[13,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [35]:
inv(array4) # array4 ni teskarisini qaytaradi

array([[ 0.08333333, -0.16666667,  0.08333333],
       [-0.16666667, -2.66666667,  1.83333333],
       [ 0.08333333,  2.5       , -1.58333333]])