<a href="https://colab.research.google.com/github/lazizbeksadullaev/telegram-bot/blob/main/Index_slice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# I. 1D massivlarda indexlash va kesib olish

In [2]:
array1 = np.arange(10, 100, 10)
array1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
array1[0]

10

In [7]:
array1[-1]

90

In [9]:
array2 = array1[3:5]#  [3;5) -chigacha eltlarni kesib oladi
array2

array([40, 50])

In [11]:
array2*2

array([ 80, 100])

In [12]:
array1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
array2[:] =  # Qachonki biz kesib olingan qismni o'zgartrsak e'tibor bering 
# asosiy kesilgan array1 ham o'zgaradi, arraysa are chunki mutable
array2

array([0, 0])

In [16]:
array1 # Bu 15-qatordagi va 12chi linedagi array1 larni solishtring array1 ham o'zgardi,
# qachinki uning kesikini o'zgartrganimizda.

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [18]:
# Agar bunday bo'lishini hohlamasak copy metodidan foydalanishimiz kere
# unda keling yangu array3 yaratamiz:

In [19]:
array3 = np.arange(10, 100, 10) # xuddi array1 ni o'ziga o'xshash
array3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
sliced_array3 = array3[3:5].copy()
sliced_array3[:] = 0
sliced_array3

array([0, 0])

In [23]:
array3 # pastki natijada ko'rishimiz mumknki biz array3 ni nusxasini sliced_array3 ga berganimiz uchun
# sliced_array3 ustida qancha amal bajarsak ham array3 ning o'zi o'zgarmiy qolaveradi

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
# II. 2D(2 o'lchovli massiv)larda indexlash va kesib olish

In [25]:
array2d = np.array([[1,2,3], [4,5,6], [7,8,9]])# shape=(3,3) bo'lgan 2 o'lchovli massiv
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# Keling bu array2d ni o'lchamini ko'ramiz burun o'rgangan ndim yordamida

In [27]:
array2d.ndim

2

In [28]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
array2d[1][1] # bunday qilib ham 

5

In [31]:
array2d[1, 1]# bunday qilib ham eltariga murojaat qilish mumkin ekan

5

In [32]:
# Keling endi 2d massivlarda kesib olish qanday bo'lishini ko'rsak

In [35]:
sl_array2d = array2d[2, 1:3] # 2- qator 1-ustun eltidan 3)-ustun eltigacha(3 kirmidi) kesib olish
sl_array2d

array([8, 9])

In [37]:
# Yoki yuqoridagi kesishni quyidagicha ham qilish mumkin
sl_array2d = array2d[2, 1:] # Bu esa 2-qator 1-ustun elti(1-eltdan) ohirigacha kesib ol
# degan buyruq bo'ladi

In [38]:
sl_array2d

array([8, 9])

In [39]:
# Va yana keling quyidagi kesishlarni ham qilaylik

In [40]:
sl_array2d1 = array2d[2, :]# array2d ni 2-qatorini hamma eltini kesib olish
sl_array2d1

array([7, 8, 9])

In [42]:
sl_array2d2 = array2d[:, :2]# array2d ni hamma qatorlaridagi 0-va 1-ustun eltlarigacha kesib olish
sl_array2d2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [44]:
# III. 3D(3 0'lchovli massiv)larda indexlash va kesib olish, telegram 
# lazizbek_sadullaev da Abdulaziz aka uchun 3D ni qidirib rasmini ko'ring:
# Quyidagi 3d arrayni qarimiz:

In [45]:
array3d = np.array([[[0, 1, 2],
                     [3, 4, 5],  # Bu 2 o'lchovli masiv indexi 0
                     [6, 7, 8]],
                    
                    [[9,10,11],
                     [12,13,14], # Bu 2 o'lchovli masiv indexi 1
                     [15,16,17]],
                    
                    [[18,19,20],
                     [21,22,23], # Bu 2 o'lchovli masiv indexi 2
                     [24,25,26]]])

In [46]:
array3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
# Misol uchun keling 0 chi 2d masivimizga quyidagicha murojat qilamiz:
array3d[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
# Endi bu 2 o'lchovli massivni olib olganimizdan keyin uning hohlagan eltiga murojat qila olamiz, 
# Keling bu 0-qatlam massivining 5 qiymatli eltini qanday olib olamiz?

In [50]:
array3d[0][1, 2] # manosi 0-2d massivning 1-qator 2-ustun eltini olib ber degan yozuv

5

In [51]:
# Huddi shunday 1-, 2- qatlamdagi 2d massivlarga ham murojat qilishimz mumkin:

In [52]:
array3d[1][:2, 1:] # kesib olishni bajaraylik:

array([[10, 11],
       [13, 14]])

In [ ]:
# Just great!!!S