<a href="https://colab.research.google.com/github/lazizbeksadullaev/telegram-bot/blob/main/malumotlar_turi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
array1 = np.array([1,2,3], dtype=np.float64)# bu float 64 malumot turiga ega massiv

In [4]:
array1

array([1., 2., 3.])

In [5]:
array2 = np.array([4,5,6], dtype=np.int32) # bu int32 malumot turiga ega massiv
array2

array([4, 5, 6], dtype=int32)

In [6]:
# etibor bersak bu yerda array1 va array2 natijalarida array2 da dtype turi ham qaytdi array1 da aesa yo'q.
# lekin havotrga o'rin yo'q, bunda har bir massivning malumot turini olish dtype(data type) nomli metod bor:

In [8]:
array1.dtype

dtype('float64')

In [9]:
array2.dtype # massiv malumot turini aniqlash

dtype('int32')

In [10]:
# Bir turdagi malumot turidan 2-turdagi malumot turiga o'tish

In [11]:
# 

In [13]:
array3 = np.array([1,2,3,4]) # Mana shunday array metodi ichiga iteravtive object yuborganimizda bu iterativening hamma eltlari
# butun sonlar bo'sa va biz dtype ni ko;rstamasak numpy avtomatik array3 ni int64 deb hisoblaydi
array3

array([1, 2, 3, 4])

In [14]:
array3.dtype # int64 ni qaytaradi

dtype('int64')

In [18]:
# Endi int64 dagi array3 ni float64 ga o'girishni o'rganamiz:
# buning uchun numpyda astype(dtype) ko'rinishdagi metod bor

In [19]:
float_arr = array3.astype(np.float64)
float_arr

array([1., 2., 3., 4.])

In [20]:
float_arr.dtype # float_arr ni date type ni tekkshirib ko'rsak:

dtype('float64')

In [21]:
# Note that, float turidagi dtypedan int dtype ga o'tganda yo'qotishlar bo'lishi mumkin.
# menimcha butun qismlarni olib intlab ketsa kerak

In [27]:
data1 = np.array([6, 5.7, 1.8, 4]) # aytganmizdek dtypeni ko'rsatmasak ham numpy iterative ichidagi
# 1 ta bo'lsa ham haqiqiy sonni ko'rib olsa unga float64 dtype berib ketadi
data1

array([6. , 5.7, 1.8, 4. ])

In [28]:
data1.dtype

dtype('float64')

In [29]:
# Keling endi bu data1 float64 dtype massivni int64 dtype massivga o'tirsak ko'ramiz nimalar yo'qotishimizni

In [31]:
int_data1 = data1.astype(np.int64) # astype dan foydalanib masivni dtype ni o'zgartirish
int_data1 # demak hamam eltlarni faqat butun qismini olib ketarkan. qolgan qismini tawab yuboradi

array([6, 5, 1, 4])

In [32]:
int_data1.dtype # keling int_data1  ji dtypeni ko;ramiz

dtype('int64')