<a href="https://colab.research.google.com/github/lazizbeksadullaev/telegram-bot/blob/main/statistik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# matematik va statistik amallar:

In [2]:
import numpy as np

In [3]:
# sum - arraydagi barcha eltlar yig'indisi
# mean - o'rtacha
# std - standart og'ish
# var - variatsiya
# cumsum - cumulative(yigilib boradigan) yig'indi
# cumprod - cumulative(yigilib boradigan) ko'paytma

In [4]:
# data yaratib olaylik
array1 = np.random.rand(5,4)# o\'lchami 5x4 lik bo'lgan tasodifiy sonladan iborat masiv yaratb beradi
array2 = np.random.rand(5,4)
array1

array([[0.78805693, 0.50215396, 0.83173945, 0.50420469],
       [0.96350399, 0.09408748, 0.3378862 , 0.79951237],
       [0.15470816, 0.49885651, 0.63664368, 0.50581189],
       [0.82763594, 0.73377485, 0.09834631, 0.04762477],
       [0.39483558, 0.48662768, 0.90227621, 0.44714969]])

In [5]:
array2

array([[0.48768852, 0.69094749, 0.48650247, 0.37600936],
       [0.9739895 , 0.43896875, 0.70170971, 0.44979914],
       [0.90626628, 0.36145766, 0.68433408, 0.33687536],
       [0.65065823, 0.2376424 , 0.84011973, 0.88528038],
       [0.02409606, 0.56396854, 0.95596503, 0.72819666]])

In [6]:
array1.sum()# yoki buni boshqacha hamm ishlatish mumkin

10.555436348658384

In [7]:
np.sum(array1)

10.555436348658384

In [8]:
array1.sum(axis=1)# Masivlarda kelishib olingan o'qlar mavjud. 
# Vertikal o'q yuqoridan pastga yo'nalgan 0-o'q
# chapdan o'nga yo'nalgan gorizantal o'q- 1-o'q ekan. a
# Demak agar biz qachon axis=0 desak vertikal o'qlarni(yuqidan-pastga) nazarda tutgan bo'lamiz va aksincha
# axis=1 desak esa gorizantal(chapdan-o'nga) o'qlarni nazarda tutgan bo'lar ekanmiz:

array([2.62615503, 2.19499004, 1.79602025, 1.70738187, 2.23088916])

In [9]:
#sum(gorizantal_lines)=array([2.55240286, 2.83280704, 2.22042338, 2.06885317, 1.59074521])
#                             0-qatr yi   1-q yig'si  2-qat yigi  3-qator yi  4-qr yig'si

In [10]:
# Ustunlar bo'yicha yig'indi hisoblamoqchi bo'sak axis=0,
# chunki 0-o'q vertikal o'q sanalardi

In [11]:
array1.sum(axis=0)# vertikal ustunlar yig'indisini hisoblaydi

array([3.1287406 , 2.31550048, 2.80689186, 2.3043034 ])

In [12]:
# mean metodi

In [13]:
data1 = np.arange(5)# sodda massiv tuzib u ustida mean ni ko'ramiz

In [14]:
mean = np.sum(data1)/len(data1)
mean

2.0

In [15]:
# numpy mean
np.mean(data1)

2.0

In [16]:
data1.mean()# data1 ning meanini olish uchuun ikisi ham o'rinli

2.0

In [17]:
array1

array([[0.78805693, 0.50215396, 0.83173945, 0.50420469],
       [0.96350399, 0.09408748, 0.3378862 , 0.79951237],
       [0.15470816, 0.49885651, 0.63664368, 0.50581189],
       [0.82763594, 0.73377485, 0.09834631, 0.04762477],
       [0.39483558, 0.48662768, 0.90227621, 0.44714969]])

In [18]:
# Bu array1 ni meanini hisoblaylik
np.mean(array1)

0.5277718174329192

In [19]:
# Huddi ustun va qatorlardagidek har bir ustun va qatorlar mean ini hisoblaylik
np.mean(array1, axis=0)# vertikaliga yuqoridan pastga har bir ustun mean ini hisoblash

array([0.62574812, 0.4631001 , 0.56137837, 0.46086068])

In [20]:
np.mean(array1, axis=1)# bu esa gorizontaliga chapdan o'nga har bir qator mean ini hisoblash
# np.mean(array1, axis=1)==array1.mean(axis=1) kabi ham ishlatish mumkin, 
# o'zingizga yoqqaniga o'rganib olishingiz mumkin

array([0.65653876, 0.54874751, 0.44900506, 0.42684547, 0.55772229])

In [22]:
array1.mean(axis=1)# korishungiz mumkinki yuqoridagi 20-qatordagi kod bilan bir hil

array([0.65653876, 0.54874751, 0.44900506, 0.42684547, 0.55772229])

In [23]:
# cumsum - cumulative sum-jamlanib(yig'ilib) boradigan yig'indi

In [26]:
data1

array([0, 1, 2, 3, 4])

In [27]:
data1.cumsum()# data1 ning oz'ini har bir eltini o'zidan oldingi eltlarini 
# yig'indisini massiv qilib qaytaradi

array([ 0,  1,  3,  6, 10])

In [28]:
np.cumsum(data1)# 27-linening alternative 

array([ 0,  1,  3,  6, 10])

In [30]:
array1

array([[0.78805693, 0.50215396, 0.83173945, 0.50420469],
       [0.96350399, 0.09408748, 0.3378862 , 0.79951237],
       [0.15470816, 0.49885651, 0.63664368, 0.50581189],
       [0.82763594, 0.73377485, 0.09834631, 0.04762477],
       [0.39483558, 0.48662768, 0.90227621, 0.44714969]])

In [29]:
array1.cumsum()# array1 ning oz'ini har bir eltini o'zidan oldingi eltlarini 
# yig'indisini massiv qilib qaytaradi

array([ 0.78805693,  1.29021089,  2.12195034,  2.62615503,  3.58965902,
        3.6837465 ,  4.0216327 ,  4.82114507,  4.97585324,  5.47470975,
        6.11135344,  6.61716533,  7.44480127,  8.17857612,  8.27692243,
        8.32454719,  8.71938278,  9.20601045, 10.10828666, 10.55543635])

In [34]:
array1.cumsum().ndim # 2.6261+0.9635=3.5896
# demak bu cumsum() 1D massivga joylab beradi, 
# biza array1 ga mos shapedagi massiv olish ucuhun uni quyidagicha 
# reshape(array1.shape) qilsak arra1 ni shape iga olib lekib beradi cumsum qaytargan 1D massivni

1

In [36]:
np.cumsum(array1).reshape(array1.shape)# 34-qatordagi ishni qilib berdi
# np.cumsum(array1).reshape(array1.shape)==array1.cumsum().reshape(array1.shape) qilish ham mumkin
# men hozir 2 yo'lini ham o'rganib olay deb 2 sini ham qo'llayapman

array([[ 0.78805693,  1.29021089,  2.12195034,  2.62615503],
       [ 3.58965902,  3.6837465 ,  4.0216327 ,  4.82114507],
       [ 4.97585324,  5.47470975,  6.11135344,  6.61716533],
       [ 7.44480127,  8.17857612,  8.27692243,  8.32454719],
       [ 8.71938278,  9.20601045, 10.10828666, 10.55543635]])

In [37]:
array1.cumsum().reshape(array1.shape)

array([[ 0.78805693,  1.29021089,  2.12195034,  2.62615503],
       [ 3.58965902,  3.6837465 ,  4.0216327 ,  4.82114507],
       [ 4.97585324,  5.47470975,  6.11135344,  6.61716533],
       [ 7.44480127,  8.17857612,  8.27692243,  8.32454719],
       [ 8.71938278,  9.20601045, 10.10828666, 10.55543635]])

In [39]:
array1

array([[0.78805693, 0.50215396, 0.83173945, 0.50420469],
       [0.96350399, 0.09408748, 0.3378862 , 0.79951237],
       [0.15470816, 0.49885651, 0.63664368, 0.50581189],
       [0.82763594, 0.73377485, 0.09834631, 0.04762477],
       [0.39483558, 0.48662768, 0.90227621, 0.44714969]])

In [40]:
# Bu array1 ni ham menimcha axislar bo'yicha cumsum qilish mumkin
array1.cumsum(axis=0)# har bir vertikal ustun bo'yicha yuqoridan pastga cumsum qilib boradi

array([[0.78805693, 0.50215396, 0.83173945, 0.50420469],
       [1.75156091, 0.59624145, 1.16962566, 1.30371706],
       [1.90626908, 1.09509796, 1.80626934, 1.80952895],
       [2.73390502, 1.82887281, 1.90461565, 1.85715372],
       [3.1287406 , 2.31550048, 2.80689186, 2.3043034 ]])

In [41]:
# buni qatorlar bo'yicha ham cumsum qilish mumkin
array1.cumsum(axis=1)# horizontally makes cumulative sum

array([[0.78805693, 1.29021089, 2.12195034, 2.62615503],
       [0.96350399, 1.05759147, 1.39547767, 2.19499004],
       [0.15470816, 0.65356468, 1.29020836, 1.79602025],
       [0.82763594, 1.56141079, 1.6597571 , 1.70738187],
       [0.39483558, 0.88146326, 1.78373947, 2.23088916]])

In [42]:
# keling bir taqqoslash qilaylikchi endi. Manashu qator bilan 36,37-qatorlarni koramiz:
np.cumsum(array1, axis=1) == np.cumsum(array1).reshape(array1.shape)
# yoki array1.cumsum(axis=1) == array1.cumsum().reshape(array1.shape)->line 37 look!

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [43]:
np.cumsum(array1).reshape(array1.shape)

array([[ 0.78805693,  1.29021089,  2.12195034,  2.62615503],
       [ 3.58965902,  3.6837465 ,  4.0216327 ,  4.82114507],
       [ 4.97585324,  5.47470975,  6.11135344,  6.61716533],
       [ 7.44480127,  8.17857612,  8.27692243,  8.32454719],
       [ 8.71938278,  9.20601045, 10.10828666, 10.55543635]])

In [ ]:
# chunki np.cumsum(array1, axis=1) qilganimiz har bir qator bo'yicha alohida cumsum qiladi while
# np.cumsum(array1).reshape(array1.shape) esa 
# umumiy boshidan (0,0) eltdan toki(4,4) eltgacha cumsum() qildi