<a href="https://colab.research.google.com/github/lazizbeksadullaev/telegram-bot/blob/main/takrorlanmas_metodlar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Takrorlanams metodlar:
# unique, in1d, setdiff1d

In [ ]:
import numpy as np

In [ ]:
# data
names = np.array(["sarvar", 'abdurahmon', 'hasan', 'temur', 'sarvar', 'temur'])
ints= np.array([3,3,3,2,2,1,1,4,4])

In [ ]:
# unique-massivdagi takrorlanmas eltlani qaytaradi, takrorlansa 1 tasini olib qaytaradi
np.unique(names)# namesdagi takrorlanmas eltlani qaytaradi, takrorlansa ham 1 tasini oladi
# va qaytgan result massiv sorted versionda keladi

array(['abdurahmon', 'hasan', 'sarvar', 'temur'], dtype='<U10')

In [ ]:
# aslida unique = set ni o'zi bu numpyda
set(names)# names ni set qildik

{'abdurahmon', 'hasan', 'sarvar', 'temur'}

In [ ]:
array1 = np.arange(6)
array2 = np.arange(4, 8)
array3 = np.arange(10, 15)

In [ ]:
array1

array([0, 1, 2, 3, 4, 5])

In [ ]:
array2

array([4, 5, 6, 7])

In [ ]:
np.in1d(array1, array2)# array1 ning qaysi eltlari array2 da bolikini jadvali
# qaytgan bool massiv 1st (teslanyatrgan)argument uzunlikina teng bo'ladi

array([False, False, False, False,  True,  True])

In [ ]:
np.isin(array1, array2)#  array1 ning qaysi eltlari array2 da bolikini jadvali
# qaytgan bool massiv 1st (teslanyatrgan)argument uzunlikina teng bo'ladi

array([False, False, False, False,  True,  True])

In [ ]:
array1

array([0, 1, 2, 3, 4, 5])

In [ ]:
array2

array([4, 5, 6, 7])

In [ ]:
np.isin(array2, array1)# arary 2 ni ihtiyoriy eltini olib shu array1 da bomi testlab ko'radi 
# agar shu elt bsa olingan eltni o'rnida True qiymatli massiv quriladi

array([ True,  True, False, False])

In [ ]:
array1

array([0, 1, 2, 3, 4, 5])

In [ ]:
array2

array([4, 5, 6, 7])

In [ ]:
# setdiff1D(arr1, arr2) # (arr1\arr2) - to'plamla ustidagi ayirma o'xshidi arr1-arr2
np.setdiff1d(array1, array2)

array([0, 1, 2, 3])

In [ ]:
array3

array([10, 11, 12, 13, 14])

In [ ]:
np.setdiff1d(array2, array3)

array([4, 5, 6, 7])