<a href="https://colab.research.google.com/github/lazizbeksadullaev/telegram-bot/blob/main/tartiblash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Numpy. Massivga yo'naltirilgandasturlash.
# 11.Tartiblash(Sorting)

In [4]:
import numpy as np

In [5]:
# data yarataylik:
array1 = np.random.randn(4) # 4 ta tasodifiy sonlardan tashkil topgan massiv
array1

array([ 0.60848729, -0.04260765,  0.06883904, -0.87104926])

In [6]:
array2 = np.random.rand(4)# aslida men ham bu randn bn rand o'rtasidagi farqda adashaman, 
# bu farq normal numpy.random.rand draws from a uniform distribution and 
# np.random.randn() from a normal distribution. "Why does initial weights drawn 
# from a normal distribution work better in deep learning" is more suited for 
# Cross Validated though. This is not related to numpy or a deep learning framework at all. –ayhan Nov 11, 2017 at 16:46
# https://stackoverflow.com/questions/47240308/differences-between-numpy-random-rand-vs-numpy-random-randn-in-python
array2

array([0.84133658, 0.59929004, 0.16193409, 0.7641264 ])

In [7]:
# randn- random normal - normal taqsimot
# rand-uniform - tekis taqsimot. Bularni har birini ishlatishga qulay
# bo'lgan o'rinlar mavjud buni keyinroq chuqur o'rganamiz: 
# Hozircha bizai holda 2 sini ham ishlatsa bo'laveradi

In [8]:
array1

array([ 0.60848729, -0.04260765,  0.06883904, -0.87104926])

In [11]:
# 1-usul
sorted_array1 = np.sort(array1) # array1 ning tartiblangan versiaysi
sorted_array1

array([-0.87104926, -0.04260765,  0.06883904,  0.60848729])

In [16]:
# 2-usul
array1.sort() # array1 ning tartiblangan versiyasi bb bu qiymat return 
# qilmas ekan array1 ning o'zini o'zgartiradi, numpy ni ichidagi sort() esa
# qiymat return qiladi
array1

array([-0.87104926, -0.04260765,  0.06883904,  0.60848729])

In [17]:
# teskari tartibda tartiblash
# afsuski numpyda teskari tartiblash uchun aniq bir parametr 
# yo'q pythonda reversed=True qilganimizdek. Buni quyidagicha matematik 
# fint ishlatib qilamiz:

In [19]:
reversed_array1 = -np.sort(-array1)# array1 ni -1 ga ko'paytrsak eng katta elt 
# eng kichik bo'lib massiv hosil bo'ldi uni sortlab qaytadan -1 ga ko'paytrsak manfiylar
# musbat bo'lib qoladi va yakunda teskari tartiblangan massivga kelamiz
reversed_array1

array([ 0.60848729,  0.06883904, -0.04260765, -0.87104926])

In [20]:
# 2D massivlarda sortlash

In [22]:
array2d = np.random.randn(2,4) # 2x4 lik normal tasodifiy sonlardan massiv yasimiz:
array2d

array([[ 1.11518805,  0.66627958, -0.88348469, -0.62828961],
       [ 0.21991912, -1.03091588,  1.24466223,  2.11238761]])

In [23]:
# Odatda 2D+ o'lchovli masivla ustida amal bajarganda axis larga tayangan 
# holda ishlar edik(yani malum bir axis ustida). 
# Bu sortlash ham horizontally(axis=1), or vertically(axis=0) kabi bo'ladi

In [25]:
array2d.sort(axis=0)# vertical yuqoridan pastga sortlash
array2d

array([[ 0.21991912, -1.03091588, -0.88348469, -0.62828961],
       [ 1.11518805,  0.66627958,  1.24466223,  2.11238761]])

In [33]:
np.sort(array2d, axis=0) # yuqoridagi ishni qilib beradi faqat return qilib massiv yuboradi

array([[-1.03091588, -0.88348469, -0.62828961,  0.21991912],
       [ 0.66627958,  1.11518805,  1.24466223,  2.11238761]])

In [34]:
array2d.sort(axis=1)# horizontal chapdan o'nga sortlash, 
# lekin bu array2d ni ichini o'zgartrib sortlidi lekin massiv qaytarmidi
# shu sababdan arary2d ni qayatadan chop qilish kerak
array2d

array([[-1.03091588, -0.88348469, -0.62828961,  0.21991912],
       [ 0.66627958,  1.11518805,  1.24466223,  2.11238761]])

In [35]:
row_sorted = np.sort(array2d, axis=1) # yuqoridagi ishni qilib beradi faqat return qilib massiv yuboradi
row_sorted

array([[-1.03091588, -0.88348469, -0.62828961,  0.21991912],
       [ 0.66627958,  1.11518805,  1.24466223,  2.11238761]])