<a href="https://colab.research.google.com/github/lazizbeksadullaev/telegram-bot/blob/main/zero_nb_numpyda_ishlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
list1 = list(range(100000)) # python list 0-99999 gacha sonlar -> Normal 
array1 = np.array(range(100000)) # numpy array(massiv) 0-99999 -> Vektorlashgan

In [5]:
%time for _ in range(10): [x*2 for x in list1] # normal hisoblash

CPU times: user 78.2 ms, sys: 16.2 ms, total: 94.4 ms
Wall time: 95.9 ms


In [7]:
time for _ in range(10): array1*2 # Vektorlashgan hisoblash

CPU times: user 3.36 ms, sys: 27 µs, total: 3.39 ms
Wall time: 3.05 ms


In [8]:
95.9/3.05

31.442622950819676

In [9]:
# Numpyda massivlar yaratish:

In [10]:
# I. Array funsiyasi yordamida:

In [ ]:
# umumiy qoidasi numpy.array(iterative_object)

In [11]:
data1 = [1,2,34, 56] # list
array1 = np.array(data1) # numpayda array

In [12]:
data1

[1, 2, 34, 56]

In [13]:
array1

array([ 1,  2, 34, 56])

In [14]:
data2 = (5, 6 ,7, 8)# tuple 
array2 = np.array(data2) # tuple bilan array yaratish

In [15]:
# Massiv o'lchamini aniqlash

In [16]:
array1.ndim # array1 ning o'lchamini chiqarib beradi

1

In [17]:
array2.ndim # arary2 ning o'lchami

1

In [18]:
# Ikki o'lchamliu va undan ortiq o'lchamli massivlarni yaratish:

In [20]:
data3 = [[1,2,3,4], [5,6,7,8]]# list ichida listladan nested  listladan foydalanamiz
array3 = np.array(data3)

In [21]:
array3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
data4 = [[1,2,3], [4,5,6], [7,8,9], [0,1,2]]
array4 = np.array(data4)

In [23]:
data4

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, 1, 2]]

In [25]:
data4.ndim

AttributeError: ignored

In [24]:
array4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [27]:
array4.ndim

2

In [29]:
array3.ndim

2

In [30]:
array4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [31]:
array4.ndim

2

In [32]:
array4.shape # qator va ustunlar sonini tuple(q, ust) ko'rinishda ko'rsatadi

(4, 3)

In [33]:
array4.size # array4  massivdagi barcha eltlar sonini ko'rsatadi

12

In [34]:
# II. Maasivlarni boshqacha usulda yaratish: zeros va ones metodlari

In [35]:
array5 = np.zeros(shape=(2, 4)) # barcha eltlari 0 gateng 2 qator va 4 ta ustundan iborat barcha ellari nolga teng massiv yaratish

In [36]:
array5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
array6 = np.ones(shape=(2, 4)) # barcha eltlari 1 ga teng 2 qator va 4 ustunli massiv hosil qilish

In [40]:
array6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
# III. Maasivlarni arange funksiyasi yordamida hosil qilish:

In [42]:
# Bu arange o'zimizni range dek genarator faaqqat massiv hosil qilishda ishlatiladi:

In [43]:
array7 = np.arange(4, 20, 2) # [4;20) sonlarni 2 qadam bilan  massivga joylab beradi
array7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
array8 = np.arange(20)# [0; 20) qiymatlarni 1 qadam bn massivga joylab beradi
array8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
# Misol1: eltlari ihitiyoriy n ta(n>0, butunn son) bo'lgan 1 o'lchamli massiv(array) yaratuvchi funksiya tuzing:
# array yoki random funksiyalaridan foydalanishingiz mumkin
import random
random.sample(range(2*10), 10)

[11, 7, 2, 12, 13, 9, 10, 5, 4, 0]

In [49]:
import random
def one_dim(n: int):
  """ n ta eltdan tashkil topgan 1 o'lchamli massiv qaytarish """
  return np.array(random.sample(range(2*n), n))

In [51]:
# Masala2: Shakli shape(r,c) bo'lgan 2 o'lchamli massiv(array) qaytaruvchi funksiya yarating
# Numpy kutubxonasida massivlar yaratuvchi funksiyalarning istalganidan foydalanishingiz mumkin

In [ ]:
def two_dim(r, c):
  """ r ta qator, c ta ustundan tshkil topgan 2 o'lchamli massiv yaratish """
  return np.ones(shape=(r,c))